site_name: Name-o-Tron 9000 Docs
site_url: https://name-o-tron.kirilov.dev
site_description: "User guide and reference for Name-o-Tron 9000"
docs_dir: docs
theme:
  name: material
  logo: assets/name-o-tron-9000.svg
  favicon: assets/name-o-tron-9000.svg
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - Downloads: releases.md
  - Features: features.md
  - Settings: settings.md
  - Tips & Best Practices: tips.md
  - FAQ: faq.md
  - Community: https://name-o-tron.kirilov.dev/community/public/
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

